import project1 from "../assets/projects/project1.jpg";
import project2 from "../assets/projects/project2.jpg";
import project3 from "../assets/projects/project3.jpg";
import project4 from "../assets/projects/project4.png";
import project5 from "../assets/projects/project5.png";
import project6 from "../assets/projects/project6.png";
import project7 from "../assets/projects/project7.png";
import "../i18n";

export const HERO_CONTENT = `I am a developer who is passionate about building robust and scalable web applications. With hands-on experience gained during my education, I have honed my skills in front-end technologies such as React, HTML, CSS, JS, Bootstrap and back-end technologies including Node.js, PHP, Java, PostgreSQL and MySQL. My goal is to use my expertise to create innovative solutions that drive business growth and deliver exceptional user experiences.`;

export const ABOUT_TEXT = `Graduated in Systems Analysis and Development from Instituto Federal Farroupilha - Campus Alegrete, currently doing a postgraduate degree in Web Technologies and Innovations at FAVENI. With experience in several technologies, such as Java, Node.js, JavaScript, HTML, CSS, PHP and Bootstrap, I have developed a solid foundation in both front-end and back-end. I also have knowledge of PostgreSQL and MySQL databases, as well as agile methodologies. Recently, I have been delving deeper into React and Tailwind, with the aim of exploring new possibilities in software development and improving my technical skills. Outside of studies, I enjoy reading, watching series and movies, and exploring new technologies.`;

export const EXPERIENCES = [
  {
    year: "December/2024 - to date",
    role: "Internship",
    company: "Civil Registry Office for Natural Persons and Special Registries",
    description: `Development of a web system for the Lux Revestimentos e Acabamentos store`,
    technologies: [
      "React.js",
      "Node.js",
      "Express.js",
      "Tailwind CSS",
      "Axios",
      "Software Design",
      "MongoDB",
      "Vercel",
      "Hostinguer",
      "Vite",
      "JWT",
    ],
  },
  {
    year: "June/2024 - November/2024",
    role: "Trainee Programmer",
    company: "Compass UOL",
    description: `My responsibilities included:
- Documentation: Complete creation of the project's technical documentation, ensuring clarity and organization for the team.
- Development: Active participation in the initial programming, using best practices and collaborating in the structuring of the system.`,
    technologies: [
      "Node.js",
      "Draw.io",
      "System Architecture",
      "Teamwork",
      "Software Documentation",
      "AWS",
    ],
  },
  {
    year: "January/2023 - June/2023",
    role: "Blockchain Developer Internship",
    company: "Compass UOL",
    description: `- Deepening your knowledge of Blockchain and AWS technologies.
- Participation in workshops and practical classes, focusing on creating smart contracts and scalable applications.
- Project development, applying knowledge in programming and innovation.
- Team collaboration, improving problem-solving and group work skills.`,
    technologies: [
      "Node.js",
      "Agile Methodologies",
      "Postman API",
      "HMTL5",
      "Blockchain",
      "JavaScript",
      "Solidity",
    ],
  },
];

export const PROJECTS = [
  {
    title: "Stock Manager",
    image: project1,
    repo: "https://github.com/acaf02/StockManager",
    description:
      "Stock Manager is a web application developed as a Final Course Project (TCC) to manage the stock control of supplies at Instituto Federal Farroupilha - Campus Alegrete. The system aims to facilitate inventory management by allowing users to register, edit, view supplies and generate reports efficiently.",
    technologies: [
      "HTML",
      "CSS",
      "Bootstrap",
      "JavaScript",
      "JQuery",
      "Ajax",
      "PHP",
      "MySQL",
      "XAMPP",
    ],
  },
  {
    title: "Portfolio Website",
    image: project2,
    repo: "https://github.com/acaf02/portfolio",
    description:
      "A personal portfolio website to showcase projects, skills, publications, organizations, and contact information.",
    technologies: ["React", "JavaScript", "Tailwind", "Node.js"],
  },
  {
    title: "A1 Team Final Project",
    image: project3,
    repo: "https://github.com/acaf02/ProjetoFinal-TimeA1",
    description:
      "The idea developed addresses the creation of NFTs for loyalty, with the theme of a pet shop where for every 10 baths the person receives a personalized NFT of their own pet generated by this application, obtaining the NFT can bring several benefits such as discounts on the next baths and participation in special promotions!",
    technologies: ["Node.js", "Docker"],
  },
  {
    title: "Lumus Solem",
    image: project4,
    repo: "https://github.com/acaf02/lumus-solem",
    description:
      "This project contains the source code for the front-end of the e-commerce Lumus Solem, a brand dedicated to creating scented candles.",
    technologies: [
      "React",
      "Tailwind",
      "Vite",
      "Node.js",
      "Express.js",
      "MongoDB",
      "JWT",
      "Cloudinary",
      "Vercel",
    ],
  },
  {
    title: "Pet Shop Institutional Website",
    image: project5,
    repo: "https://github.com/acaf02/petshop-institutional-site",
    description:
      "This project provides a professional and easy-to-use online presence for pet shops.",
    technologies: [
      "Node.js",
      "React",
      "Tailwind CSS",
      "Express",
      "Vercel",
      "Vite",
    ],
  },
  {
    title: "My Library",
    image: project6,
    repo: "https://github.com/acaf02/MyLibrary",
    description:
      "It features my personal collection of physical books along with memorable quotes from each one.",
    technologies: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "Node.js",
      "jQuery",
      "Webpack",
    ],
  },
  {
    title: "Rock, Paper e Scissors",
    image: project7,
    repo: "https://github.com/acaf02/rock-paper-scissors",
    description: "A simple implementation of the Rock, Paper, Scissors game.",
    technologies: ["HTML5", "CSS3", "Pyton"],
  },
];

export const PUBLICATION = [
  {
    title:
      "Experiencing integrated experiences of systems analysis and development: learning and development in a practical context.",
    publication: "XIV Mostra da Educação Profissional e Tecnológica",
    url: "https://arandu.iffarroupilha.edu.br/handle/itemid/452",
    description:
      "Interdisciplinary project in the Systems Analysis and Development (ADS) course, focused on the development of an application for recording and monitoring the Service Bulletins of the Municipal Guard of Alegrete. The project integrated disciplines such as Software Engineering, Database, Programming and Human-Computer Interface (IHC), addressing all phases of the software development life cycle. " +
      "My work included requirements gathering, UML modeling, database development in PostgreSQL, and creation of stories and epics for feature management. I worked closely with City Guard representatives and classmates to refine and enhance the application, ensuring it met the specific needs of the organization.",
  },
  {
    title:
      "StockManager: a software for controlling food stocks in the IFFAR cafeteria - Alegrete Campus",
    publication: "XV Mostra da Educação Profissional e Tecnológica",
    url: "https://arandu.iffarroupilha.edu.br/handle/itemid/540",
    description:
      "Page: 788" +
      "Abstract: Stocks play an important role in business management. Effective stock management helps to avoid excess and shortages of products, thus contributing to the optimization of investment and maximizing the efficiency of the company's internal resources. Based on this context, this paper proposes the development of customized software for the control of food inputs in the Instituto Federal Farroupilha cafeteria - Alegrete Campus, aiming to improve and optimize the control and administration of all available products. To achieve these objectives, a software development methodology based on the waterfall model was used, ensuring that each stage is completed before the next one begins.",
  },
  {
    title:
      "CHEMICALL: Chemical product management system for laboratories of Federal Institutes, a case study IFFarroupilha",
    publication: "XV Mostra da Educação Profissional e Tecnológica",
    url: "https://arandu.iffarroupilha.edu.br/handle/itemid/540",
    description:
      "Page: 785" +
      "Abstract: Efficient management of chemical products in laboratories is essential to ensure the safety, control and proper use of these materials. In this context, this work aims to develop a specific chemical inventory management software for the Chemistry Laboratories of the Instituto Federal Farroupilha. This software will be developed based on the Sommerville cascade method and with the completion of this work it is expected to optimize the registration and removal of chemical products from the inventory, display the usage status of chemical products already existing in the institution and issue a report with the status and inventory of all currently available products.",
  },
];

export const ORGANIZATION = [
  {
    title: "Diretório Acadêmico Ada Augusta Byron King",
    role: "Treasurer and Communications Director",
    period: "June 2024 - February 2025",
    description: `
I was Treasurer and Communications Director for the Academic Board of the Systems Analysis and Development course at the Instituto Federal Farroupilha (IFFAR). My responsibilities included:

- Financial management: As treasurer, I was responsible for the financial control of the Academic Board's activities, managing resources efficiently to ensure the holding of events and initiatives that benefit students.

- Communication and promotion of the course: As Communications Director, I led the creation and execution of communication strategies to publicize the Academic Board's activities, promote the course and strengthen the group's identity. This included managing social media, preparing promotional materials and organizing campaigns to expand the reach of our initiatives.

- Planning and organizing academic events: I actively contributed to the planning and execution of events such as Academic Week, workshops and lectures. My work involved both logistical support and communication with speakers, partners and participants, aiming at the success of the events and the engagement of the academic community.

- Student support: I facilitated communication between students and course coordinators, acting as a channel of dialogue to identify and meet students' needs. I also collaborated in the creation of initiatives that improve the academic experience and promote students' personal and professional development.
`,
  },
];

export const ACADEMY = [
  {
    title: "Analysis and Development of Systems",
    where: "Instituto Federal Farroupilha - Campus Alegrete",
    period: "February 2022 - January 2025",
    description:
      "As a student of Analysis and Systems Development, I am developing skills in programming, database modeling, and software engineering. The course provides a practical and theoretical view of the stages of system creation, covering everything from requirements analysis to software development. Through projects and practical activities, I am improving my skills in current technologies and agile methodologies, broadening my knowledge and abilities in the field.",
  },
  {
    title: "Web Technologies and Innovations",
    where: "FAVENI",
    period: "January 2025 - August 2026",
    description: "Postgraduate studies in web technologies and innovations.",
  },
  {
    title: "Advanced English",
    where: "Senac - Alegrete",
    period: "August 2016 - June 2020",
    description:
      "I started my journey in language learning, with the aim of expanding my professional and personal horizons, improving my communication in English to operate in the global market.",
  },
];

export const CONTACT = {
  email: "anacarol.alves1@outlook.com",
};
